//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViTrader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViTrader.Properties.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation mail failed to send.
        /// </summary>
        internal static string ActivationError {
            get {
                return ResourceManager.GetString("ActivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDT added successfully:.
        /// </summary>
        internal static string AddedUSDT {
            get {
                return ResourceManager.GetString("AddedUSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add USDT.
        /// </summary>
        internal static string AddingUSDTError {
            get {
                return ResourceManager.GetString("AddingUSDTError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AdminPrivilegesNo {
            get {
                return ResourceManager.GetString("AdminPrivilegesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AdminPrivilegesYes {
            get {
                return ResourceManager.GetString("AdminPrivilegesYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will now exit.
        /// </summary>
        internal static string AppExitMsg {
            get {
                return ResourceManager.GetString("AppExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will now restart.
        /// </summary>
        internal static string AppRestartMsg {
            get {
                return ResourceManager.GetString("AppRestartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully bought crypto: .
        /// </summary>
        internal static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your mail to activate the account.
        /// </summary>
        internal static string CheckMail {
            get {
                return ResourceManager.GetString("CheckMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        internal static string ComboBoxCap {
            get {
                return ResourceManager.GetString("ComboBoxCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ComboBoxPrice {
            get {
                return ResourceManager.GetString("ComboBoxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string ComboBoxVol {
            get {
                return ResourceManager.GetString("ComboBoxVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete your account and all trades and positions associated with the account. Are you sure you wish to proceed?.
        /// </summary>
        internal static string DeleteUserWarning {
            get {
                return ResourceManager.GetString("DeleteUserWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting user.
        /// </summary>
        internal static string DeletingUserError {
            get {
                return ResourceManager.GetString("DeletingUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already in use.
        /// </summary>
        internal static string EmailExistsError {
            get {
                return ResourceManager.GetString("EmailExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-mail address.
        /// </summary>
        internal static string EmailValidationError {
            get {
                return ResourceManager.GetString("EmailValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to server.
        /// </summary>
        internal static string FailedToConnectError {
            get {
                return ResourceManager.GetString("FailedToConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        internal static string FailedToLoginError {
            get {
                return ResourceManager.GetString("FailedToLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register.
        /// </summary>
        internal static string FailedToRegisterError {
            get {
                return ResourceManager.GetString("FailedToRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate your account.
        /// </summary>
        internal static string InactiveAccount {
            get {
                return ResourceManager.GetString("InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect credentials.
        /// </summary>
        internal static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading chart.
        /// </summary>
        internal static string LoadingChartError {
            get {
                return ResourceManager.GetString("LoadingChartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading cryptos.
        /// </summary>
        internal static string LoadingCryptosError {
            get {
                return ResourceManager.GetString("LoadingCryptosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading positions.
        /// </summary>
        internal static string LoadingPositionsError {
            get {
                return ResourceManager.GetString("LoadingPositionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading trades.
        /// </summary>
        internal static string LoadingTradesError {
            get {
                return ResourceManager.GetString("LoadingTradesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading user.
        /// </summary>
        internal static string LoadingUserError {
            get {
                return ResourceManager.GetString("LoadingUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string MatchError {
            get {
                return ResourceManager.GetString("MatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least 8 characters including a number.
        /// </summary>
        internal static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered successfully.
        /// </summary>
        internal static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sold crypto: .
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must add more than 100 and less than 10000 USDT.
        /// </summary>
        internal static string USDTAmountError {
            get {
                return ResourceManager.GetString("USDTAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists.
        /// </summary>
        internal static string UserNameExistsError {
            get {
                return ResourceManager.GetString("UserNameExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have between 4 and 9 characters and can not start with a number.
        /// </summary>
        internal static string UserNameValidationError {
            get {
                return ResourceManager.GetString("UserNameValidationError", resourceCulture);
            }
        }
    }
}
